export const ORDERS = [
  {
    id: 1,
    price: "N 3450",
    title: "Asparagus",
    image: require("../../assets/asparagus.jpg"),
    origin: "Ajah",
    destination: "Lekki",
    date: "27-09-2022",
    delivered: true,
    description:
      "This is a development-only warning and won't be shown in production. ",
  },
  {
    id: 2,
    price: "N 2450",
    title: "Eclair",
    image: require("../../assets/eclair.jpg"),
    origin: "Abijo",
    destination: "Sangotedo",
    date: "25-09-2022",
    delivered: true,
    description: "It is a long established fact that a reader will be. ",
  },
  {
    id: 3,
    price: "N 1750",
    title: "Meat",
    image: require("../../assets/spaghetti.jpg"),
    origin: "Victoria Island",
    destination: "Oshodi",
    date: "23-09-2022",
    delivered: false,
    description:
      "distracted by the readable content of a page when looking at its layout. ",
  },
  {
    id: 4,
    price: "N 1750",
    title: "Meat",
    image: require("../../assets/meat.jpg"),
    origin: "Victoria Island",
    destination: "Oshodi",
    date: "23-09-2022",
    delivered: false,
    description:
      "It is a long readable content of a page when looking at its layout. ",
  },
  {
    id: 5,
    price: "N 1750",
    title: "Meat",
    image: require("../../assets/spaghetti.jpg"),
    origin: "Bariga",
    destination: "Yaba",
    date: "23-09-2022",
    description: "It is a long established fact that a reader will be layout. ",
  },
  {
    id: 6,
    price: "N 1750",
    title: "Fish",
    image: require("../../assets/salmon.jpg"),
    origin: "Ojota",
    destination: "Berger",
    date: "23-09-2022",
    delivered: false,
    description:
      "This is a development-only warning and won't be shown in production. ",
  },
  {
    id: 7,
    price: "N 1750",
    title: "Eggs",
    image: require("../../assets/meat.jpg"),
    origin: "Victoria Island",
    destination: "Oshodi",
    date: "23-09-2022",
    delivered: true,
    description:
      "This is a development-only warning and won't be shown in production. ",
  },
  {
    id: 8,
    price: "N 1750",
    title: "Meat",
    image: require("../../assets/asparagus.jpg"),
    origin: "Awoyaya",
    destination: "Ikorodu",
    date: "23-09-2022",
    delivered: true,
    description:
      "This is a development-only warning and won't be shown in production. ",
  },
  {
    id: 9,
    price: "N 1750",
    title: "Meat",
    image: require("../../assets/eclair.jpg"),
    origin: "Victoria Island",
    destination: "Oshodi",
    date: "23-09-2022",
    delivered: true,
    description:
      "This is a development-only warning and won't be shown in production. ",
  },
  {
    id: 10,
    price: "N 1750",
    title: "Meat",
    image: require("../../assets/eclair.jpg"),
    origin: "Victoria Island",
    destination: "Oshodi",
    date: "23-09-2022",
    delivered: false,
    description:
      "This is a development-only warning and won't be shown in production. ",
  },
  {
    id: 11,
    price: "N 1750",
    title: "Meat",
    image: require("../../assets/eclair.jpg"),
    origin: "Victoria Island",
    destination: "Oshodi",
    date: "23-09-2022",
    delivered: false,
    description:
      "This is a development-only warning and won't be shown in production. ",
  },
  {
    id: 12,
    price: "N 1750",
    title: "Meat",
    image: require("../../assets/eclair.jpg"),
    origin: "Victoria Island",
    destination: "Oshodi",
    date: "23-09-2022",
    delivered: false,
    description:
      "This is a development-only warning and won't be shown in production. ",
  },
];
